# Generated by Django 3.2.6 on 2021-08-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210822_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='defailt.jpg', null=True, upload_to=''),
        ),
    ]
