# Generated by Django 3.2.6 on 2021-09-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210901_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='create',
            new_name='created',
        ),
    ]
